### ISSUE TITLE
TypeScript本体がエラー。Nodeバージョンが問題か。

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3core#134]
TypeScript本体がエラー。Nodeバージョンが問題のようなので、
tscコンパイラバージョンを調べる。
必要なら、古いNode.jsのバージョンのチェックを外す。

**Comment by weyk** [comment]
nodejs 14.xの場合、eslintのpeerパッケージかなにかインストールができずにwarningがでるんですよね。
runtimeとしてインストーする場合は影響しないとは思うので、14.xはもうすぐEOLということもあり、
対応は不要のような気がします。
ずっと開発環境を保持していると気が付きづらいので、ある程度頻繁にlockファイルとnode_modulesを
削除してnpm installでログを見るのは必要かもしれません。

**Comment by kujirahand** [comment]
そうなんですね！こちら解決済みとします。ありがとうございます。
